
/**
 * PULSE AI - Professional PDF Generator Utility
 * Provides consistent, branded PDF styling across the application
 */

import jsPDF from 'jspdf';
import { format } from 'date-fns';

// Brand Colors
const COLORS = {
  primary: '#7C3AED',
  primaryDark: '#6D28D9',
  secondary: '#1E293B',
  text: '#475569',
  textMuted: '#64748B',
  border: '#E2E8F0',
  success: '#22C55E',
  warning: '#EAB308',
  danger: '#EF4444',
  background: '#F8FAFC',
  white: '#FFFFFF'
};

/**
 * Initialize a new PDF document with standard settings
 */
export function createPDF(orientation = 'portrait') {
  const doc = new jsPDF({
    orientation,
    unit: 'mm',
    format: 'a4'
  });
  
  return doc;
}

/**
 * Add branded header to the page
 * @param {Object} doc - jsPDF document instance
 * @param {string} title - Header title text
 * @param {Object} user - User object with full_name
 * @param {string} brandColor - Optional brand color hex (e.g., '#7C3AED')
 */
export function addHeader(doc, title, user, brandColor) {
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Use provided brandColor, or fall back to the default primary color
  const headerBgColor = brandColor || COLORS.primary;
  
  // Header background
  doc.setFillColor(headerBgColor);
  doc.rect(0, 0, pageWidth, 25, 'F');
  
  // Title
  doc.setTextColor(COLORS.white);
  doc.setFontSize(18);
  doc.setFont(undefined, 'bold');
  doc.text(title, 20, 12);
  
  // User info and date
  doc.setFontSize(9);
  doc.setFont(undefined, 'normal');
  doc.text(`Generated by ${user?.full_name || 'PULSE AI'}`, 20, 18);
  doc.text(format(new Date(), 'MMMM dd, yyyy'), pageWidth - 20, 18, { align: 'right' });
  
  return 30; // Return starting Y position for content
}

/**
 * Add branded footer with page numbers
 */
export function addFooter(doc, pageNumber, totalPages) {
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Footer line
  doc.setDrawColor(COLORS.border);
  doc.setLineWidth(0.5);
  doc.line(20, pageHeight - 15, pageWidth - 20, pageHeight - 15);
  
  // Footer text
  doc.setTextColor(COLORS.textMuted);
  doc.setFontSize(8);
  doc.text('Powered by PULSE AI', 20, pageHeight - 10);
  doc.text(`Page ${pageNumber} of ${totalPages}`, pageWidth - 20, pageHeight - 10, { align: 'right' });
  doc.text('Confidential - For Internal Use Only', pageWidth / 2, pageHeight - 10, { align: 'center' });
}

/**
 * Add a section header
 */
export function addSectionHeader(doc, title, yPos) {
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(COLORS.secondary);
  doc.text(title, 20, yPos);
  
  // Underline
  const textWidth = doc.getTextWidth(title);
  doc.setDrawColor(COLORS.primary);
  doc.setLineWidth(0.8);
  doc.line(20, yPos + 1, 20 + textWidth, yPos + 1);
  
  return yPos + 8;
}

/**
 * Add a metric card
 */
export function addMetricCard(doc, x, y, width, height, label, value, change = null) {
  // Card background
  doc.setFillColor(COLORS.background);
  doc.roundedRect(x, y, width, height, 2, 2, 'F');
  
  // Border
  doc.setDrawColor(COLORS.border);
  doc.setLineWidth(0.3);
  doc.roundedRect(x, y, width, height, 2, 2, 'S');
  
  // Label
  doc.setFontSize(9);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(COLORS.textMuted);
  doc.text(label, x + 5, y + 6);
  
  // Value
  doc.setFontSize(16);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(COLORS.secondary);
  doc.text(value, x + 5, y + 15);
  
  // Change indicator
  if (change !== null) {
    const changeText = `${change >= 0 ? '+' : ''}${change.toFixed(1)}%`;
    const changeColor = change >= 0 ? COLORS.success : COLORS.danger;
    doc.setFontSize(8);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(changeColor);
    doc.text(changeText, x + 5, y + height - 4);
  }
}

/**
 * Draw a professional table
 */
export function drawTable(doc, startY, headers, data, columnWidths = null) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const tableWidth = pageWidth - (margin * 2);
  
  // Auto-calculate column widths if not provided
  if (!columnWidths) {
    const numCols = headers.length;
    columnWidths = Array(numCols).fill(tableWidth / numCols);
  }
  
  let y = startY;
  const rowHeight = 8;
  const cellPadding = 2;
  
  // Draw header
  doc.setFillColor(COLORS.secondary);
  doc.rect(margin, y, tableWidth, rowHeight, 'F');
  
  doc.setTextColor(COLORS.white);
  doc.setFontSize(10);
  doc.setFont(undefined, 'bold');
  
  let xPos = margin;
  headers.forEach((header, i) => {
    doc.text(header, xPos + cellPadding, y + rowHeight / 2 + 1, { baseline: 'middle' });
    xPos += columnWidths[i];
  });
  
  y += rowHeight;
  
  // Draw data rows
  doc.setFont(undefined, 'normal');
  doc.setFontSize(9);
  
  data.forEach((row, rowIndex) => {
    // Alternating row colors
    if (rowIndex % 2 === 1) {
      doc.setFillColor(COLORS.background);
      doc.rect(margin, y, tableWidth, rowHeight, 'F');
    }
    
    doc.setTextColor(COLORS.text);
    xPos = margin;
    
    row.forEach((cell, i) => {
      const cellText = String(cell);
      doc.text(cellText, xPos + cellPadding, y + rowHeight / 2 + 1, { baseline: 'middle' });
      xPos += columnWidths[i];
    });
    
    y += rowHeight;
    
    // Check for page break
    if (y > doc.internal.pageSize.getHeight() - 30) {
      doc.addPage();
      y = 30;
      
      // Redraw header on new page
      doc.setFillColor(COLORS.secondary);
      doc.rect(margin, y, tableWidth, rowHeight, 'F');
      doc.setTextColor(COLORS.white);
      doc.setFontSize(10);
      doc.setFont(undefined, 'bold');
      
      xPos = margin;
      headers.forEach((header, i) => {
        doc.text(header, xPos + cellPadding, y + rowHeight / 2 + 1, { baseline: 'middle' });
        xPos += columnWidths[i];
      });
      
      y += rowHeight;
      doc.setFont(undefined, 'normal');
      doc.setFontSize(9);
    }
  });
  
  return y + 5;
}

/**
 * Add a text block with word wrapping
 */
export function addTextBlock(doc, text, x, y, maxWidth, fontSize = 10) {
  doc.setFontSize(fontSize);
  doc.setTextColor(COLORS.text);
  doc.setFont(undefined, 'normal');
  
  const lines = doc.splitTextToSize(text, maxWidth);
  doc.text(lines, x, y);
  
  return y + (lines.length * (fontSize * 0.35)) + 5;
}

/**
 * Add a status badge
 */
export function addStatusBadge(doc, text, x, y, status = 'default') {
  const statusColors = {
    success: { bg: '#DCFCE7', text: '#16A34A' },
    warning: { bg: '#FEF3C7', text: '#CA8A04' },
    danger: { bg: '#FEE2E2', text: '#DC2626' },
    info: { bg: '#DBEAFE', text: '#2563EB' },
    default: { bg: COLORS.background, text: COLORS.text }
  };
  
  const color = statusColors[status] || statusColors.default;
  
  const padding = 2;
  const height = 5;
  doc.setFontSize(8);
  const textWidth = doc.getTextWidth(text);
  
  // Badge background
  doc.setFillColor(color.bg);
  doc.roundedRect(x, y - height + 1, textWidth + (padding * 2), height, 1, 1, 'F');
  
  // Badge text
  doc.setTextColor(color.text);
  doc.setFont(undefined, 'bold');
  doc.text(text, x + padding, y - 1);
  
  doc.setFont(undefined, 'normal');
}

/**
 * Add a divider line
 */
export function addDivider(doc, y) {
  const pageWidth = doc.internal.pageSize.getWidth();
  doc.setDrawColor(COLORS.border);
  doc.setLineWidth(0.5);
  doc.line(20, y, pageWidth - 20, y);
  return y + 5;
}

/**
 * Check if we need a page break and add one if necessary
 */
export function checkPageBreak(doc, currentY, requiredSpace = 40) {
  const pageHeight = doc.internal.pageSize.getHeight();
  
  if (currentY + requiredSpace > pageHeight - 30) {
    doc.addPage();
    return 30; // Return new starting Y position
  }
  
  return currentY;
}

/**
 * Format currency for display
 */
export function formatCurrency(value) {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0
  }).format(value || 0);
}

/**
 * Format number with commas
 */
export function formatNumber(value) {
  return new Intl.NumberFormat('en-US').format(value || 0);
}
